// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {history} from '../models';
import {config} from '../models';
import {desktop} from '../models';

export function ClearHistory():Promise<void>;

export function GetHistory(arg1:number,arg2:number):Promise<Array<history.Record>>;

export function GetSettings():Promise<config.Settings>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function StartRecording():Promise<void>;

export function StopAndProcess():Promise<desktop.ProcessResult>;
