// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['desktop']['App']['ClearHistory']();
}

export function ClearShortcut() {
  return window['go']['desktop']['App']['ClearShortcut']();
}

export function DeleteAllData() {
  return window['go']['desktop']['App']['DeleteAllData']();
}

export function GetDefaultBuiltInRules() {
  return window['go']['desktop']['App']['GetDefaultBuiltInRules']();
}

export function GetDefaultProfiles() {
  return window['go']['desktop']['App']['GetDefaultProfiles']();
}

export function GetHistory(arg1, arg2) {
  return window['go']['desktop']['App']['GetHistory'](arg1, arg2);
}

export function GetLogPath() {
  return window['go']['desktop']['App']['GetLogPath']();
}

export function GetPasteStatus() {
  return window['go']['desktop']['App']['GetPasteStatus']();
}

export function GetCapabilities() {
  return window['go']['desktop']['App']['GetCapabilities']();
}

export function GetPlatform() {
  return window['go']['desktop']['App']['GetPlatform']();
}

export function GetRecentLogs(arg1) {
  return window['go']['desktop']['App']['GetRecentLogs'](arg1);
}

export function GetSettings() {
  return window['go']['desktop']['App']['GetSettings']();
}

export function GetShortcut() {
  return window['go']['desktop']['App']['GetShortcut']();
}

export function GetVersion() {
  return window['go']['desktop']['App']['GetVersion']();
}

export function HotkeyCapabilities() {
  return window['go']['desktop']['App']['HotkeyCapabilities']();
}

export function IsSecretStorageSecure() {
  return window['go']['desktop']['App']['IsSecretStorageSecure']();
}

export function ListInputDevices() {
  return window['go']['desktop']['App']['ListInputDevices']();
}

export function ListModelsForConnection(arg1) {
  return window['go']['desktop']['App']['ListModelsForConnection'](arg1);
}

export function ListProviders() {
  return window['go']['desktop']['App']['ListProviders']();
}

export function SaveSettings(arg1) {
  return window['go']['desktop']['App']['SaveSettings'](arg1);
}

export function SetShortcut(arg1) {
  return window['go']['desktop']['App']['SetShortcut'](arg1);
}

export function StartRecording() {
  return window['go']['desktop']['App']['StartRecording']();
}

export function StopAndProcess() {
  return window['go']['desktop']['App']['StopAndProcess']();
}

export function TestPrompt(arg1, arg2) {
  return window['go']['desktop']['App']['TestPrompt'](arg1, arg2);
}
