// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {history} from '../models';
import {desktop} from '../models';

export function ClearHistory():Promise<void>;

export function GetDefaultProfiles():Promise<Array<config.RefinementProfile>>;

export function GetHistory(arg1:number,arg2:number):Promise<Array<history.Record>>;

export function GetPlatform():Promise<desktop.PlatformInfo>;

export function GetSettings():Promise<config.Settings>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function StartRecording():Promise<void>;

export function StopAndProcess():Promise<desktop.ProcessResult>;

export function TestPrompt(arg1:string,arg2:string):Promise<desktop.ProcessResult>;
