// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['desktop']['App']['ClearHistory']();
}

export function GetHistory(arg1, arg2) {
  return window['go']['desktop']['App']['GetHistory'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['desktop']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['desktop']['App']['SaveSettings'](arg1);
}

export function StartRecording() {
  return window['go']['desktop']['App']['StartRecording']();
}

export function StopAndProcess() {
  return window['go']['desktop']['App']['StopAndProcess']();
}
